// =============================================================================
// Seed Data — based on real 119th Congress bills (as of Feb 2026)
// Used as fallback when no API keys are configured.
// =============================================================================

import type { Bill } from '../types';

export const SEED_BILLS: Bill[] = [
  {
    id: 'HR-3479',
    title: 'SECURE American Telecommunications Act',
    shortTitle: 'SECURE Telecom Act',
    chamber: 'House',
    billNumber: 'H.R. 3479',
    status: 'In Committee',
    introduced: '2025-05-20',
    lastAction: 'Referred to Subcommittee on Science, Technology, Communications',
    lastActionDate: '2025-05-22',
    category: 'Telecom',
    sectors: ['Telecom', 'Cybersecurity'],
    summary: 'Strengthens security requirements for American telecom networks, including supply chain integrity and equipment standards for critical infrastructure.',
    sponsors: ['Rep. Frank Lucas (R-OK)'],
    cosponsors: 12,
    committees: ['House Energy and Commerce'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3479',
    tags: ['5G', 'Supply Chain', 'National Security'],
  },
  {
    id: 'S-1651',
    title: 'Lowering Broadband Costs for Consumers Act of 2025',
    shortTitle: 'Broadband Costs Act',
    chamber: 'Senate',
    billNumber: 'S. 1651',
    status: 'In Committee',
    introduced: '2025-05-13',
    lastAction: 'Referred to Committee on Commerce, Science, and Transportation',
    lastActionDate: '2025-05-13',
    category: 'Telecom',
    sectors: ['Telecom', 'Broadband'],
    summary: 'Seeks to reduce broadband costs for consumers through increased competition and transparency mandates for internet service providers.',
    sponsors: ['Sen. Ben Ray Luján (D-NM)'],
    cosponsors: 8,
    committees: ['Senate Commerce, Science, and Transportation'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/1651',
    tags: ['Broadband', 'Consumer Protection', 'ISP Regulation'],
  },
  {
    id: 'S-3268',
    title: 'Streamlining Telecom & Broadband Deployment in Rights-of-Way',
    shortTitle: 'ROW Deployment Act',
    chamber: 'Senate',
    billNumber: 'S. 3268',
    status: 'Introduced',
    introduced: '2025-11-20',
    lastAction: 'Introduced in Senate',
    lastActionDate: '2025-11-20',
    category: 'Telecom',
    sectors: ['Telecom', 'Broadband', 'Transportation'],
    summary: 'Amends the Communications Act of 1934 to streamline deployment of telecom and broadband facilities in public and railroad rights-of-way.',
    sponsors: ['Sen. John Thune (R-SD)'],
    cosponsors: 4,
    committees: ['Senate Commerce, Science, and Transportation'],
    impactLevel: 'Medium',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/3268',
    tags: ['Rights-of-Way', 'Broadband Deployment', 'Permitting'],
  },
  {
    id: 'S-2869',
    title: 'Federal Spectrum Use Reporting Act',
    shortTitle: 'Spectrum Reporting Act',
    chamber: 'Senate',
    billNumber: 'S. 2869',
    status: 'Introduced',
    introduced: '2025-09-25',
    lastAction: 'Referred to Committee on Commerce, Science, and Transportation',
    lastActionDate: '2025-09-25',
    category: 'Telecom',
    sectors: ['Telecom'],
    summary: 'Requires NTIA to issue annual reports on federal spectrum usage in certain frequency bands for improved allocation transparency.',
    sponsors: ['Sen. Mike Lee (R-UT)'],
    cosponsors: 3,
    committees: ['Senate Commerce, Science, and Transportation'],
    impactLevel: 'Medium',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/2869',
    tags: ['Spectrum', 'NTIA', 'Wireless'],
  },
  {
    id: 'HR-1873',
    title: 'Broadband Grant Tax Treatment Act',
    shortTitle: 'Broadband Tax Act',
    chamber: 'House',
    billNumber: 'H.R. 1873',
    status: 'In Committee',
    introduced: '2025-03-05',
    lastAction: 'Referred to the Committee on Ways and Means',
    lastActionDate: '2025-03-05',
    category: 'Telecom',
    sectors: ['Telecom', 'Broadband', 'Tax'],
    summary: 'Excludes broadband infrastructure grants from gross income, including BEAD program and USDA broadband grants.',
    sponsors: ['Rep. Mike Kelly (R-PA)', 'Rep. Jimmy Panetta (D-CA)'],
    cosponsors: 22,
    committees: ['House Ways and Means'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/1873',
    tags: ['Tax', 'Broadband Grants', 'BEAD Program', 'Bipartisan'],
  },
  {
    id: 'S-3565',
    title: 'BEAD Program Remaining Funds Authorization Act',
    shortTitle: 'BEAD Funds Act',
    chamber: 'Senate',
    billNumber: 'S. 3565',
    status: 'Introduced',
    introduced: '2025-12-18',
    lastAction: 'Introduced in Senate',
    lastActionDate: '2025-12-18',
    category: 'Telecom',
    sectors: ['Telecom', 'Broadband'],
    summary: 'Authorizes remaining BEAD Program funds for competitive subgrants supporting broadband deployment projects.',
    sponsors: ['Sen. Shelley Moore Capito (R-WV)'],
    cosponsors: 5,
    committees: ['Senate Commerce, Science, and Transportation'],
    impactLevel: 'Medium',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/3565',
    tags: ['BEAD', 'Broadband Deployment', 'IIJA'],
  },
  {
    id: 'S-3682',
    title: 'Power for the People Act of 2026',
    shortTitle: 'Power for the People Act',
    chamber: 'Senate',
    billNumber: 'S. 3682',
    status: 'Introduced',
    introduced: '2026-01-15',
    lastAction: 'Referred to Committee on Energy and Natural Resources',
    lastActionDate: '2026-01-15',
    category: 'Energy',
    sectors: ['Energy', 'Utilities'],
    summary: 'Addresses energy grid impacts from data centers and crypto mining. Requires FERC reporting, establishes utility rate classes for high-demand facilities.',
    sponsors: ['Sen. Edward Markey (D-MA)'],
    cosponsors: 7,
    committees: ['Senate Energy and Natural Resources'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/3682',
    tags: ['Data Centers', 'Energy Grid', 'Rate Classes', 'FERC'],
  },
  {
    id: 'HR-1235',
    title: 'Federal Infrastructure Bank Act of 2025',
    shortTitle: 'Infrastructure Bank Act',
    chamber: 'House',
    billNumber: 'H.R. 1235',
    status: 'In Committee',
    introduced: '2025-02-11',
    lastAction: 'Referred to House Committee on Financial Services',
    lastActionDate: '2025-02-13',
    category: 'Infrastructure',
    sectors: ['Infrastructure', 'Finance'],
    summary: 'Establishes a Federal Infrastructure Bank for loans, equity investments, and loan guarantees for revenue-producing infrastructure projects, with 10% rural allocation.',
    sponsors: ['Rep. Rosa DeLauro (D-CT)'],
    cosponsors: 18,
    committees: ['House Financial Services'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/1235',
    tags: ['Infrastructure Bank', 'Federal Financing', 'Rural'],
  },
  {
    id: 'HR-3548',
    title: 'Infrastructure Expansion Act of 2025',
    shortTitle: 'Infrastructure Expansion Act',
    chamber: 'House',
    billNumber: 'H.R. 3548',
    status: 'In Committee',
    introduced: '2025-05-15',
    lastAction: 'Referred to House Committee on Transportation and Infrastructure',
    lastActionDate: '2025-05-16',
    category: 'Infrastructure',
    sectors: ['Infrastructure', 'Transportation'],
    summary: 'Preserves federal financial assistance for infrastructure and transportation, with new liability standards for federally-funded projects.',
    sponsors: ['Rep. Nicole Malliotakis (R-NY)'],
    cosponsors: 9,
    committees: ['House Transportation and Infrastructure'],
    impactLevel: 'Medium',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3548',
    tags: ['Federal Assistance', 'Liability', 'Transportation'],
  },
  {
    id: 'HR-6590',
    title: 'No Bonuses for Utility Executives Act',
    shortTitle: 'No Utility Bonuses Act',
    chamber: 'House',
    billNumber: 'H.R. 6590',
    status: 'Introduced',
    introduced: '2025-12-05',
    lastAction: 'Referred to House Committee on Energy and Commerce',
    lastActionDate: '2025-12-05',
    category: 'Energy',
    sectors: ['Utilities', 'Energy'],
    summary: 'Limits executive bonuses at electric utilities that have experienced significant service failures or safety violations.',
    sponsors: ['Rep. Greg Casar (D-TX)'],
    cosponsors: 6,
    committees: ['House Energy and Commerce'],
    impactLevel: 'Medium',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/6590',
    tags: ['Executive Compensation', 'Utility Accountability'],
  },
  {
    id: 'S-3585',
    title: 'Consumer-Regulated Electric Utilities Federal Exemption Act',
    shortTitle: 'Utility Federal Exemption Act',
    chamber: 'Senate',
    billNumber: 'S. 3585',
    status: 'Introduced',
    introduced: '2025-12-19',
    lastAction: 'Referred to Committee on Energy and Natural Resources',
    lastActionDate: '2025-12-19',
    category: 'Energy',
    sectors: ['Utilities', 'Energy'],
    summary: 'Amends the Federal Power Act to exempt consumer-regulated electric utilities from certain federal regulations.',
    sponsors: ['Sen. Steve Daines (R-MT)'],
    cosponsors: 3,
    committees: ['Senate Energy and Natural Resources'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/3585',
    tags: ['Federal Power Act', 'Deregulation', 'State Oversight'],
  },
  {
    id: 'HR-5566',
    title: 'Water Infrastructure Resilience & Sustainability Act',
    shortTitle: 'Water Resilience Act',
    chamber: 'House',
    billNumber: 'H.R. 5566',
    status: 'In Committee',
    introduced: '2025-09-25',
    lastAction: 'Referred to House Committee on Energy and Commerce',
    lastActionDate: '2025-09-25',
    category: 'Water',
    sectors: ['Water', 'Infrastructure'],
    summary: 'Reauthorizes Clean Water Act and Safe Drinking Water Act programs focused on water infrastructure resilience.',
    sponsors: ['Rep. Debbie Dingell (D-MI)'],
    cosponsors: 14,
    committees: ['House Energy and Commerce'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/5566',
    tags: ['Clean Water Act', 'Safe Drinking Water', 'Reauthorization'],
  },
  {
    id: 'HR-4553',
    title: 'Energy and Water Development Appropriations Act, 2026',
    shortTitle: 'Energy & Water Approps FY26',
    chamber: 'House',
    billNumber: 'H.R. 4553',
    status: 'Passed House',
    introduced: '2025-07-10',
    lastAction: 'Passed the House by vote of 397-28',
    lastActionDate: '2025-09-04',
    category: 'Energy',
    sectors: ['Energy', 'Water', 'Infrastructure', 'Nuclear'],
    summary: 'FY2026 appropriations: $57.3B discretionary for Army Corps, Bureau of Reclamation, DOE, FERC, NRC. Includes $9.9B for water resources.',
    sponsors: ['Rep. Chuck Fleischmann (R-TN)'],
    cosponsors: 0,
    committees: ['House Appropriations'],
    impactLevel: 'Critical',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/4553',
    tags: ['Appropriations', 'Army Corps', 'DOE', 'Nuclear', 'Water'],
  },
  {
    id: 'S-3293',
    title: 'Energy and Water Development Appropriations Act, 2026 (Senate)',
    shortTitle: 'Energy & Water Approps FY26 (Senate)',
    chamber: 'Senate',
    billNumber: 'S. 3293',
    status: 'In Committee',
    introduced: '2025-12-01',
    lastAction: 'Introduced by Senate E&W Appropriations Subcommittee Chairman',
    lastActionDate: '2025-12-01',
    category: 'Energy',
    sectors: ['Energy', 'Water', 'Infrastructure'],
    summary: 'Senate version of FY2026 energy and water appropriations. Nearly level funding with FY2025 plus transfers of unobligated appropriations.',
    sponsors: ['Sen. John Kennedy (R-LA)'],
    cosponsors: 0,
    committees: ['Senate Appropriations'],
    impactLevel: 'Critical',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/senate-bill/3293',
    tags: ['Appropriations', 'Army Corps', 'DOE', 'Bureau of Reclamation'],
  },
  {
    id: 'HR-3928',
    title: 'Improving Water Quality Certifications & American Energy Infrastructure Act',
    shortTitle: 'Water Quality & Energy Act',
    chamber: 'House',
    billNumber: 'H.R. 3928',
    status: 'In Committee',
    introduced: '2025-06-05',
    lastAction: 'Referred to House Committee on Transportation and Infrastructure',
    lastActionDate: '2025-06-06',
    category: 'Water',
    sectors: ['Water', 'Energy', 'Infrastructure'],
    summary: 'Reforms water quality certification to accelerate energy infrastructure development while maintaining environmental protections.',
    sponsors: ['Rep. David Rouzer (R-NC)'],
    cosponsors: 11,
    committees: ['House Transportation and Infrastructure'],
    impactLevel: 'Medium',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3928',
    tags: ['Water Quality', 'Permitting Reform', 'Energy'],
  },
  {
    id: 'HR-5452',
    title: 'Safe Streets and Roads for All Program Amendments',
    shortTitle: 'Safe Streets Amendment',
    chamber: 'House',
    billNumber: 'H.R. 5452',
    status: 'In Committee',
    introduced: '2025-09-18',
    lastAction: 'Referred to House Committee on Transportation and Infrastructure',
    lastActionDate: '2025-09-18',
    category: 'Transportation',
    sectors: ['Transportation', 'Infrastructure'],
    summary: 'Modifies the IIJA\'s Safe Streets and Roads for All grant program for improved road safety project allocation.',
    sponsors: ['Rep. Seth Moulton (D-MA)'],
    cosponsors: 2,
    committees: ['House Transportation and Infrastructure'],
    impactLevel: 'Low',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/5452',
    tags: ['Road Safety', 'Grants', 'IIJA'],
  },
  // ===== Power Utilities =====
  {
    id: 'HR-3632',
    title: 'Power Plant Reliability Act of 2025',
    shortTitle: 'Power Plant Reliability Act',
    chamber: 'House',
    billNumber: 'H.R. 3632',
    status: 'In Committee',
    introduced: '2025-05-22',
    lastAction: 'Referred to House Committee on Energy and Commerce',
    lastActionDate: '2025-05-22',
    category: 'Energy',
    sectors: ['Energy', 'Utilities'],
    summary: 'Allows FERC to order power plants to remain open up to 5 years if grid reliability is at risk. Requires 5-year advance notice before retiring electric generating facilities.',
    sponsors: ['Rep. August Pfluger (R-TX)'],
    cosponsors: 15,
    committees: ['House Energy and Commerce'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3632',
    tags: ['FERC', 'Power Plants', 'Grid Reliability', 'Plant Retirement'],
  },
  {
    id: 'HR-3616',
    title: 'Reliable Power Act',
    shortTitle: 'Reliable Power Act',
    chamber: 'House',
    billNumber: 'H.R. 3616',
    status: 'In Committee',
    introduced: '2025-05-21',
    lastAction: 'Referred to House Committee on Energy and Commerce',
    lastActionDate: '2025-05-21',
    category: 'Energy',
    sectors: ['Energy', 'Utilities'],
    summary: 'Directs NERC to conduct annual long-term reliability assessments. Establishes FERC review process for federal regulations that may impact grid generation adequacy.',
    sponsors: ['Rep. Jeff Duncan (R-SC)'],
    cosponsors: 20,
    committees: ['House Energy and Commerce'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3616',
    tags: ['NERC', 'FERC', 'Grid Reliability', 'Generation Adequacy'],
  },
  {
    id: 'HR-5600',
    title: 'SPEED and Reliability Act of 2025',
    shortTitle: 'SPEED Act',
    chamber: 'House',
    billNumber: 'H.R. 5600',
    status: 'In Committee',
    introduced: '2025-09-29',
    lastAction: 'Referred to House Committee on Energy and Commerce',
    lastActionDate: '2025-09-29',
    category: 'Energy',
    sectors: ['Energy', 'Utilities', 'Infrastructure'],
    summary: 'Streamlines transmission line permitting under the Federal Power Act. Establishes national interest criteria for siting electric transmission facilities with ratepayer protections.',
    sponsors: ['Rep. Scott Peters (D-CA)', 'Rep. Andy Barr (R-KY)'],
    cosponsors: 8,
    committees: ['House Energy and Commerce'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/5600',
    tags: ['Transmission Permitting', 'Federal Power Act', 'Bipartisan', 'Grid Expansion'],
  },
  {
    id: 'HR-1047',
    title: 'GRID Power Act',
    shortTitle: 'GRID Power Act',
    chamber: 'House',
    billNumber: 'H.R. 1047',
    status: 'In Committee',
    introduced: '2025-02-05',
    lastAction: 'Referred to House Committee on Energy and Commerce',
    lastActionDate: '2025-02-06',
    category: 'Energy',
    sectors: ['Energy', 'Utilities'],
    summary: 'Requires FERC to revise interconnection request prioritization for dispatchable power projects to ensure reliable generation can connect to the grid quickly and cost-effectively.',
    sponsors: ['Rep. Brandon Williams (R-NY)'],
    cosponsors: 10,
    committees: ['House Energy and Commerce'],
    impactLevel: 'Medium',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/1047',
    tags: ['FERC', 'Interconnection', 'Dispatchable Power', 'Grid Reliability'],
  },
  {
    id: 'HR-164',
    title: 'POWER Act of 2025 — Promoting Opportunities to Widen Electrical Resilience',
    shortTitle: 'POWER Act (Resilience)',
    chamber: 'House',
    billNumber: 'H.R. 164',
    status: 'In Committee',
    introduced: '2025-01-03',
    lastAction: 'Referred to House Committee on Transportation and Infrastructure',
    lastActionDate: '2025-01-06',
    category: 'Energy',
    sectors: ['Energy', 'Utilities', 'Infrastructure'],
    summary: 'Authorizes electric utilities receiving emergency assistance to carry out cost-effective hazard mitigation to improve grid resilience and prevent future power outages.',
    sponsors: ['Rep. Garret Graves (R-LA)'],
    cosponsors: 7,
    committees: ['House Transportation and Infrastructure'],
    impactLevel: 'Medium',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/164',
    tags: ['Grid Resilience', 'Emergency Assistance', 'Power Outages', 'Hazard Mitigation'],
  },
  {
    id: 'HR-3628',
    title: 'State Planning for Reliability and Affordability Act',
    shortTitle: 'State Reliability Planning Act',
    chamber: 'House',
    billNumber: 'H.R. 3628',
    status: 'In Committee',
    introduced: '2025-05-22',
    lastAction: 'Referred to House Committee on Energy and Commerce',
    lastActionDate: '2025-05-22',
    category: 'Energy',
    sectors: ['Energy', 'Utilities'],
    summary: 'Amends PURPA to require state-regulated electric utilities to maintain reliable generation facilities or procure reliable power as part of integrated resource planning over a 10-year horizon.',
    sponsors: ['Rep. Rick Allen (R-GA)'],
    cosponsors: 12,
    committees: ['House Energy and Commerce'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3628',
    tags: ['PURPA', 'Integrated Resource Planning', 'Reliable Generation', 'State Regulation'],
  },
  {
    id: 'HR-3751',
    title: 'Reliable Grid Act',
    shortTitle: 'Reliable Grid Act',
    chamber: 'House',
    billNumber: 'H.R. 3751',
    status: 'In Committee',
    introduced: '2025-06-05',
    lastAction: 'Referred to House Committee on Energy and Commerce',
    lastActionDate: '2025-06-05',
    category: 'Energy',
    sectors: ['Energy', 'Utilities'],
    summary: 'Prohibits EPA from enforcing rules that restrict operations of electric generating units critical to grid reliability. Directs FERC and NERC to develop new reliability standards.',
    sponsors: ['Rep. Eric Burlison (R-MO)'],
    cosponsors: 3,
    committees: ['House Energy and Commerce'],
    impactLevel: 'High',
    congress: '119th',
    sourceUrl: 'https://www.congress.gov/bill/119th-congress/house-bill/3751',
    tags: ['EPA', 'Grid Reliability', 'Power Generation', 'NERC Standards'],
  },
];
